# Generated by Django 4.1.3 on 2022-11-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
                ('state', models.CharField(max_length=50, verbose_name='Страна')),
                ('population', models.IntegerField(verbose_name='Население')),
            ],
            options={
                'ordering': ['-population'],
            },
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Индекс Облачности')),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='Температура')),
                ('feels_like', models.FloatField(verbose_name='Ощущается')),
                ('temp_min', models.FloatField(verbose_name='Мин Температура')),
                ('temp_max', models.FloatField(verbose_name='Макс Температура')),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField(verbose_name='Скорость ветра')),
                ('deg', models.IntegerField(verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(verbose_name='Время обновления')),
                ('preasure', models.IntegerField(verbose_name='Давление')),
                ('humidity', models.IntegerField(verbose_name='Влажность')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.cloud')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.temp')),
                ('wind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.wind')),
            ],
        ),
    ]
