# Generated by Django 4.1.3 on 2022-11-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['-timestamp']},
        ),
    ]
