# Generated by Django 4.1.3 on 2022-11-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='preasure',
            new_name='preassure',
        ),
    ]
