# Generated by Django 4.1.3 on 2022-11-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_preasure_weather_preassure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='cloud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud', to='weather.cloud'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.temp'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_wind', to='weather.wind'),
        ),
    ]
